// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CloudPhoto.Data.Migrations
{
    public partial class AddUserSubscribeTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "UserSubscribes",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    UserSubscribedId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    SubscribeToUserId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    CreatedOn = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedOn = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedOn = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserSubscribes", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserSubscribes_AspNetUsers_SubscribeToUserId",
                        column: x => x.SubscribeToUserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_UserSubscribes_AspNetUsers_UserSubscribedId",
                        column: x => x.UserSubscribedId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserSubscribes_IsDeleted",
                table: "UserSubscribes",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_UserSubscribes_SubscribeToUserId",
                table: "UserSubscribes",
                column: "SubscribeToUserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserSubscribes_UserSubscribedId",
                table: "UserSubscribes",
                column: "UserSubscribedId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserSubscribes");
        }
    }
}
