// <auto-generated />
namespace CloudPhoto.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    [Route("api/[controller]")]
    public class TestController : Controller
    {
        // http://localhost:5000/api/test/
        [HttpGet]
        public IActionResult Getid()
        {
            string id = "0#21312";
            return this.Json(id);
        }

        // http://localhost:5000/api/test/getid
        [HttpGet("getid/", Name = "Getid")]
        public IActionResult Getid1()
        {
            string id = "1#21312";
            return this.Json(id);
        }

        // http://localhost:5000/api/test/getid1
        [HttpGet("getid1/", Name = "Getid1")]
        public IActionResult Getid2()
        {
            string id = "2#21312";
            return this.Json(id);
        }

        [HttpPost]
        public IActionResult SetId([FromForm] string name)
        {
            string id = "0#21312";
            return this.Json(id);
        }

        //[HttpPost]
        //public IActionResult SetId(string name)
        //{
        //    string id = "0#21312" + name;
        //    return this.Json(id);
        //}

        //[HttpPost("setid/")]
        //public IActionResult SetId1(string name)
        //{
        //    string id = "1#21312" + name;
        //    return this.Json(id);
        //}

        //[HttpPost("setid1/")]
        //public IActionResult SetId2(string name)
        //{
        //    string id = "2#21312" + name;
        //    return this.Json(id);
        //}
    }
}
