name: Continuous Integration and Continuous Deploy

on:
  push:
    branches:
      - master
   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:     
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .Net 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/Web/CloudPhoto.Web/CloudPhoto.Web.csproj

      - name: npm jquery install
        run: npm i --save-dev @types/jquery
      
      - name: npm jquery.cookie install
        run: npm i --save-dev @types/jquery.cookie
      
      - name: npm jqueryui install
        run: npm i --save-dev @types/jqueryui
        
      - name: Build app
        run: dotnet build ./src/Web/CloudPhoto.Web/CloudPhoto.Web.csproj -c Release --no-restore

      - name: Automated Data tests
        run:  |
          dotnet test ./src/Tests/CloudPhoto.Services.Data.Tests/CloudPhoto.Services.Data.Tests.csproj -c Release --no-build --blame
          echo "Count failed tests %ERRORLEVEL%"
          echo "Exited with '$?'"
          
      - name: Automated Web tests
        run: dotnet test ./src/Tests/CloudPhoto.Web.Tests/CloudPhoto.Web.Tests.csproj -c Release --no-build
        
      - name: Publish app
        run: dotnet publish ./src/Web/CloudPhoto.Web/CloudPhoto.Web.csproj -c Release -o ./out
