name: Continuous Integration and Continuous Deploy

on:
  push:
    branches:
      - main
    workflow_dispatch:
      - main

jobs:
  build:     
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .Net 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/Web/CloudPhoto.Web/CloudPhoto.Web.csproj

      - name: Build app
        run: dotnet build ./src/Web/CloudPhoto.Web/CloudPhoto.Web.csproj -c Release --no-restore

      - name: Automated tests
        run: dotnet test ./src/Tests/CloudPhoto.Services.Data.Tests/CloudPhoto.Services.Data.Tests.csproj -c Release --no-build
     
      - name: Publish app
        run: dotnet publish ./src/Web/CloudPhoto.Web/CloudPhoto.Web.csproj -c Release -o ./out
